package com.modelrag.agent.intent;

import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicLong; import org.springframework.beans.factory.ObjectProvider; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service;

@Service public class IntentTreeService {
    private final Map<Long,List<IntentNode>> nodes=new ConcurrentHashMap<>(); private final AtomicLong ids=new AtomicLong(); private final ObjectProvider<JdbcTemplate> jdbc;
    public IntentTreeService(ObjectProvider<JdbcTemplate> jdbc){this.jdbc=jdbc;}
    public IntentNode create(IntentNode node){validate(node);JdbcTemplate db=jdbc.getIfAvailable();if(db!=null)try{Long id=db.queryForObject("INSERT INTO kb_intent_node(dataset_id,parent_id,name,node_type,target_type,target_id,description,priority,enabled) VALUES (?,?,?,?,?,?,?,?,?) RETURNING id",Long.class,node.datasetId(),node.parentId(),node.name(),node.nodeType(),node.targetType(),node.targetId(),node.description(),node.priority(),node.enabled());return new IntentNode(id,node.datasetId(),node.parentId(),node.name(),node.nodeType(),node.targetType(),node.targetId(),node.description(),node.priority(),node.enabled());}catch(Exception ignored){}IntentNode saved=new IntentNode(ids.incrementAndGet(),node.datasetId(),node.parentId(),node.name(),node.nodeType(),node.targetType(),node.targetId(),node.description(),node.priority(),node.enabled());nodes.computeIfAbsent(node.datasetId(),ignored->new CopyOnWriteArrayList<>()).add(saved);return saved;}
    public IntentNode update(long datasetId,long id,IntentNode node){validate(new IntentNode(id,datasetId,node.parentId(),node.name(),node.nodeType(),node.targetType(),node.targetId(),node.description(),node.priority(),node.enabled()));JdbcTemplate db=jdbc.getIfAvailable();if(db!=null)try{int updated=db.update("UPDATE kb_intent_node SET parent_id=?,name=?,node_type=?,target_type=?,target_id=?,description=?,priority=?,enabled=?,update_time=NOW() WHERE dataset_id=? AND id=?",node.parentId(),node.name(),node.nodeType(),node.targetType(),node.targetId(),node.description(),node.priority(),node.enabled(),datasetId,id);if(updated==0)throw new IllegalArgumentException("意图不存在: "+id);return get(datasetId,id).orElseThrow();}catch(IllegalArgumentException e){throw e;}catch(Exception ignored){}List<IntentNode> list=nodes.getOrDefault(datasetId,new CopyOnWriteArrayList<>());for(int i=0;i<list.size();i++)if(Objects.equals(list.get(i).id(),id)){IntentNode saved=new IntentNode(id,datasetId,node.parentId(),node.name(),node.nodeType(),node.targetType(),node.targetId(),node.description(),node.priority(),node.enabled());list.set(i,saved);return saved;}throw new IllegalArgumentException("意图不存在: "+id);}
    public void delete(long datasetId,long id){JdbcTemplate db=jdbc.getIfAvailable();if(db!=null)try{int deleted=db.update("DELETE FROM kb_intent_node WHERE dataset_id=? AND id=?",datasetId,id);if(deleted==0)throw new IllegalArgumentException("意图不存在: "+id);return;}catch(IllegalArgumentException e){throw e;}catch(Exception ignored){}List<IntentNode> list=nodes.getOrDefault(datasetId,new CopyOnWriteArrayList<>());if(!list.removeIf(node->Objects.equals(node.id(),id)))throw new IllegalArgumentException("意图不存在: "+id);}
    public List<IntentNode> list(long datasetId){JdbcTemplate db=jdbc.getIfAvailable();if(db!=null)try{return db.query("SELECT id,dataset_id,parent_id,name,node_type,target_type,target_id,description,priority,enabled FROM kb_intent_node WHERE dataset_id=? ORDER BY priority DESC,id",(rs,n)->new IntentNode(rs.getLong("id"),rs.getLong("dataset_id"),rs.getObject("parent_id",Long.class),rs.getString("name"),rs.getString("node_type"),rs.getString("target_type"),rs.getString("target_id"),rs.getString("description"),rs.getInt("priority"),rs.getBoolean("enabled")),datasetId);}catch(Exception ignored){}return nodes.getOrDefault(datasetId,List.of()).stream().sorted(Comparator.comparingInt(IntentNode::priority).reversed()).toList();}
    public Optional<IntentNode> match(long datasetId,String query){String text=normalize(query);return list(datasetId).stream().filter(IntentNode::enabled).filter(node->terms(node).stream().anyMatch(text::contains)).findFirst();}
    private Optional<IntentNode> get(long datasetId,long id){return list(datasetId).stream().filter(node->Objects.equals(node.id(),id)).findFirst();}
    private void validate(IntentNode node){if(node.name()==null||node.name().isBlank())throw new IllegalArgumentException("意图名称不能为空");if(!Set.of("RAG","TOOL","DIRECT").contains(node.targetType()))throw new IllegalArgumentException("不支持的意图目标");if("TOOL".equals(node.targetType())&&(node.targetId()==null||node.targetId().isBlank()))throw new IllegalArgumentException("TOOL 意图必须绑定工具");}
    private List<String> terms(IntentNode node){List<String> values=new ArrayList<>();add(values,node.name());if(node.description()!=null)for(String term:node.description().split("[\\s,，、/|;；:：]+"))add(values,term);return values;}
    private void add(List<String> values,String term){String normalized=normalize(term);if(!normalized.isBlank()&&!values.contains(normalized))values.add(normalized);}
    private String normalize(String value){return value==null?"":value.toLowerCase(Locale.ROOT).replaceAll("[\\s,，、/|;；:：]+","");}
}
